### ISSUE TITLE
Chrome App using Firebase

### ISSUE THREAD

**Issue by vikasprogrammer** [firebase/firebase-chrome-extension#2]
I am trying to create a Chrome Packaged App using firebase but failing to do so. I search on the net about the same but had no luck finding a sample app. 

I am getting this (even after [sandboxing](https://developer.chrome.com/apps/app_external#inline_scripts) the app):

`Sandbox access violation: Blocked a frame at "chrome-extension://apaioibalkfknelijikinffdoeimgfke" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.`

`Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Sandbox access violation: Blocked a frame at "chrome-extension://apaioibalkfknelijikinffdoeimgfke" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.`

**Comment by jondthompson** [comment]
Still have to do this with angularfire in a Chrome App.
