### ISSUE TITLE
Authentication with Firebase 3.0.2 in chrome extension

### ISSUE THREAD

**Issue by adriaanlabusc** [firebase/firebase-chrome-extension#4]
Issue #1 asked for an example chrome extension that uses authentication. I'm aware of that explanation and example but I'm still stuck.

I can currently login using AuthUI and the google provider (on a hosted page) after which I get a token with `user.getToken().then(function(accessToken) {...})` and store it in local storage using a content script as done in the example app sited in #1 .

In a different content script (running on a url I don't know beforehand) I retrieve the token and try to authenticate with things like `fireBaseApp.auth().signInWithCredential(token)` or `fireBaseApp.auth(token)` etc. I get the error `This domain is not authorized for OAuth operations for your Firebase project` which is the same thing I got when using AuthUI directly from the extension instead of a hosted page.

Am I missing something fundamental here?

**Comment by alfongj** [comment]
Hi Adriaan,

Please ignore "This domain is not authorized for OAuth operations for your Firebase project", this error just affects `signInWithPopup/Redirect` (we will soon release an update that makes this message a bit clearer :) ).

Unfortunately, we currently do not have an API to directly do what you are trying to accomplish (pass a token to another Firebase auth instance to sign a user in there). 

Some workarounds you could consider would be:
1) Sending the token you get via `getToken()` to a server, [verifying it](https://firebase.google.com/docs/auth/server#verify_id_tokens) and then minting a custom auth token that you can use from your content script with `signInWithCustomToken()`
2) Caching the user credentials (e.g. in your case the google id_token or access_token that you get after a sign in) and then using that to sign in on the content script with 
```
var credential = firebase.auth.GoogleAuthProvider.credential(googleUser.getAuthResponse().id_token);
firebase.auth().signInWithCredential(credential)
```

**Comment by adriaanlabusc** [comment]
The first option, minting a custom auth token worked for me. The second option always failed for some reason.

**Comment by nicolasgarnier** [comment]
@adriaanlabusc We've now published a sample that shows how to use Google auth in a Chrome extension using the Chrome Identity API: https://github.com/firebase/quickstart-js/tree/master/auth/chromextension

**Comment by richburdon** [comment]
Answer: https://github.com/firebase/quickstart-js/issues/98

**Comment by nicolasgarnier** [comment]
👍
